[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "workbaselab-ops", email = "workbaselab@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.3",
    "langchain-agent>=0.1.1",
    "langchain-openai>=1.6.7",
    "langgraph>=1.2.12",
    "langgraph-cli[inmem]>=0.4.32",
    "python-dotenv>=1.2.3",
]
